const Images = {
    AppLogo: require("../theme/images/AppLogo.png"),
    BottomCircle: require("../theme/images/BottomCircle.png"),
    LogoBg: require("../theme/images/LogoBg.png"),
    SplashScreen: require("../theme/images/SplashScreen.png")
}

const Icons = {
    ArrowIcon: require("../theme/icons/arrowLeft.png"),
    CheckIcon: require("../theme/icons/check-mark.png"),
    CheckIconBig: require("../theme/icons/selectedBig.png"),
    NoCheckIcon: require("../theme/icons/inactiveCheck.png"),
    DummyImageIcon: require("../theme/icons/dummyImage.png"),
    EyeShowIcon: require("../theme/icons/eyeShow.png"),
    EyeHideIcon: require("../theme/icons/eyeHide.png"),
    CurrentLocationIcon: require("../theme/icons/currentLocation.png"),
    SearchIcon: require("../theme/icons/search-icon.png"),
    MenuIcon: require("../theme/icons/ico-menu.png"),
    LocationIcon: require("../theme/icons/ico-location.png"),
    BannerIcon: require("../theme/icons/bg-banner.png"),
    NonVegIcon: require("../theme/icons/ico-nonveg.png"),
    VeganIcon: require("../theme/icons/ico-vegan.png"),
    VegIcon: require("../theme/icons/ico-vegetarian.png"),
    SeaFoodIcon: require("../theme/icons/ico-sea-food.png"),
    DistanceIcon: require("../theme/icons/ico-distance.png"),
    DiscountIcon: require("../theme/icons/discount-bg.png"),
    TimingIcon: require("../theme/icons/ico-timing.png"),
    HomeIcon: require("../theme/icons/ico-home-active.png"),
    OrdersIcon: require("../theme/icons/ico-orders-active.png"),
    SavingsIcon: require("../theme/icons/ico-saving-active.png"),
    ProfileIcon: require("../theme/icons/ico-profile-active.png"),
    BakeryIcon: require("../theme/icons/Bakery.png"),
    GroceryIcon: require("../theme/icons/Grocery.png"),
    ButcherIcon: require("../theme/icons/Butcher.png"),
    VegBoxIcon: require("../theme/icons/ico-veg-box.png"),
    NonVegBoxIcon: require("../theme/icons/ico-non-veg-box.png"),
    VeganBoxIcon: require("../theme/icons/ico-vegan-box.png"),
    SeaFoodBoxIcon: require("../theme/icons/ico-sea-food-box.png"),
    CartIcon: require("../theme/icons/ico-cart.png"),
    BackIcon: require("../theme/icons/ico-back.png"),
    CloseIcon: require("../theme/icons/ico-close.png"),
    CrossIcon: require("../theme/icons/CrossIcon.png"),
    ArrowGreenIcon: require("../theme/icons/ico-arrow-green.png"),
    SelectedLargeIcon: require("../theme/icons/selectedLarge.png"),
    ReadyPickUpIcon: require("../theme/icons/ReadyPickup.png"),
    PickedUpIcon: require("../theme/icons/pickedUpCheck.png"),
    ReviewIcon: require("../theme/icons/ico-review.png"),
    SupportIcon: require("../theme/icons/ico-support.png"),
    NotificationIcon: require("../theme/icons/ico-notification.png"),
    InfoIcon: require("../theme/icons/ico-info.png"),
    ShareIcon: require("../theme/icons/ico-share.png"),
    RateIcon: require("../theme/icons/ico-rate.png"),
    DrawerHomeIcon: require("../theme/icons/ico-home-drawer.png"),
    DrawerProfileIcon: require("../theme/icons/ico-profile-drawer.png"),
    DrawerOrderIcon: require("../theme/icons/ico-order-drawer.png"),
    DrawerSavingIcon: require("../theme/icons/ico-saving-drawer.png"),
    DeleteIcon: require("../theme/icons/ico-delete.png"),
    ImportantIcon: require("../theme/icons/important.png"),
    EditIcon: require("../theme/icons/EditIcon.png"),
    InvoiceIcon: require("../theme/icons/InvoiceIcon.png"),
    ProfileEditIcon: require("../theme/icons/profile-edit.png"),
    MinusIcon: require("../theme/icons/minusIcon.png"),
    AddIcon: require("../theme/icons/addIcon.png"),
    CallIcon: require("../theme/icons/ico-call.png"),
}


export { Images, Icons }