export const FONTS = {
    muliBoldFont: "Muli-Bold",
    muliSemiBoldFont: "Muli-SemiBold",
    muliRegularFont: "Muli-Regular",
    helveticaNeueMediumFont: "HelveticaNeue Medium",
    helveticaNeueThinFont: "HelveticaNeue Thin",
    helveticaNeueBoldFont: "HelveticaNeue Bold",
    helveticaNeueRegularFont: "HelveticaNeue Light",
    poppinsSemiBoldFont: "Poppins-SemiBold",
    poppinsRegularFont: "Tenon-regular",
    poppinsMediumFont: "Tenon-medium",
    poppinsBoldFont: "Poppins-Bold",
    tenonBoldFont: "Tenon-bold",
    tenonRegularFont: "Tenon-regular",
    tenonMediumFont: "Tenon-medium",
    // workSansSemiBoldFont: "WorkSans-SemiBold",
    // workSansRegularFont: "WorkSans-Regular",
    // workSansMediumFont: "WorkSans-Medium",
}